update deps
nirgit/simple-xml-to-json pull request #48
Opened 2024-04-30 20:54 UTC by jdalton

update deps

2024-05-03 09:17 UTC, nirgit requested changes
cool. PR looks good @jdalton 👍 

two things before we merge this PR:

1. fix the build which now fails (`npm run build`)
2. see comment re unused dependency (dont forget to rebuild the package-lock after removal)

2024-05-03 09:17 UTC, nirgit commented on .gitignore
> +.idea/
already exists in line below, remove

2024-05-03 09:17 UTC, nirgit commented on package.json
> +    "@rollup/plugin-replace": "^5.0.5",
unused dependency, remove

2024-05-03 15:36 UTC, jdalton commented
Updated with issues fixed.

2024-05-04 19:19 UTC, nirgit approved these changes

2024-05-04 19:21 UTC, nirgit commented
lgtm @jdalton

2024-05-05 11:17 UTC, jdalton commented
Okay! @nirgit I lack merge rights, so I cannot merge.

2024-05-05 12:14 UTC, nirgit commented
> Okay! @nirgit I lack merge rights, so I cannot merge.

sent you an invite, after you accept, i'll set up the relevant permissions (AFAIR)

2024-05-05 21:50 UTC, merged