add support for inlining methods
nirgit/simple-xml-to-json pull request #49
Opened 2024-04-30 21:14 UTC by jdalton

add support for inlining methods

2024-05-03 09:55 UTC, nirgit requested changes
thanks @jdalton 

could you give some detailed explanation on the work done on the `rollup.config.js` part?
i don't understand what you are trying to achieve and if the code complexity tradeoff is worth it
(assuming this is done for perf optimization, it'd be helpful to see some test  measurements of "before" vs "after")

2024-05-03 09:55 UTC, nirgit commented on src/constants.js
> +        COMPTIME: true
explain?

2024-05-03 09:55 UTC, nirgit commented on src/model.js
we could probably rename this file to `src/token.js` at this point :)

2024-05-03 09:55 UTC, nirgit commented on src/constants.js
> +// Each constant is inlined by Rollup.
1. thanks for letting me know.
2. lets remove the comment

2024-05-03 09:55 UTC, nirgit commented on rollup.config.js
> +const { default: regexpPluginOriginal } = require('rollup-plugin-regexp')
this npm lib is deprecated

2024-05-03 15:39 UTC, jdalton commented on rollup.config.js
> +const { default: regexpPluginOriginal } = require('rollup-plugin-regexp')
I had that initial mixup too. It seems though it is not. Updated 5 months ago, code commit 2 months ago:
https://www.npmjs.com/package/rollup-plugin-regexp/v/5.0.1

2024-05-03 20:26 UTC, jdalton commented on src/constants.js
> +        COMPTIME: true
Languages like Zig and others have a notion of at "compile time". So when we are building the lib output with rollup and we load the modules it is at "compile time" this way during compile time we can export things that need to be inlined else not export them. The rollup "replace" plugin takes care of it seamlessly.

2024-05-03 20:27 UTC, jdalton commented on rollup.config.js
> +}
I moved the "inline" stuff to its own module. It's designed in a way that you can not inline and all the code still works. Inlining just allows code to be annotated like `peek(/*inline*/)` and it will inline the code at compile time but keep it abstracted during development.

2024-05-03 20:28 UTC, jdalton commented on package.json
> +    "build": "npm run clean && rollup -c --inline",
☝️ custom "inline" plugin command.

2024-05-03 20:32 UTC, jdalton commented on rollup.config.js
> +}
JavaScript engines perform inlining during their JIT phase. However because parsing/tokenizing/creating ast can be intensive having it inlined upfront can aid JS engines in their JIT because more things are known up-front (less calling out to other functions).

2024-05-03 20:42 UTC, jdalton commented on rollup.config.js
> +}
Withinlining enabled in PR #47 the performance is:

>After for 4,000 iterations:
>>
>> avg exec time of 4000 iterations (in ms): 0.553
>>...
>>Time: 2.459 s, estimated 3 s

without inlining _(so removing `--inline` from the run command)_ it is:

After for 4,000 iterations:
>
> avg exec time of 4000 iterations (in ms): 0.743
>...
>Time: 3.206 s

The idea is that inlining is bonus and so that's why it's an easy on/off and code works without inlining. The inlining bit is an extra oomph that does produce consistently faster results.

2024-05-05 11:16 UTC, jdalton commented
Updated to simplify the inline bits by using acorn to reduce reliance on regexp.

2024-05-06 18:18 UTC, jdalton commented on rollup.config.js
> +const { default: regexpPluginOriginal } = require('rollup-plugin-regexp')
Ended up removing this dep anyways.

2024-05-07 05:41 UTC, nirgit commented
cool stuff @jdalton sorry for the delay reviewing this, i'll try to get to this by the end of the week

any chance you're adding some unit tests to the inline plugin you wrote until then?
thanks!

2024-05-08 06:40 UTC, jdalton commented
@nirgit 
> any chance you're adding some unit tests to the inline plugin you wrote until then? thanks!

At the moment the plugin will warn if it misses an inline (you specify inlining something it doesn't have the source for) and will also throw an error for unsupported syntax (complete with snippet of code at the line and the a "^" under the identifier in question.

2024-05-10 08:59 UTC, nirgit approved these changes
since the tests pass, and it's possible to disable the inline plugin easily (thanks!) and since it's contained, i'm fine with approving this PR, although there are 2 things that are still bugging me:

1. i think that the `inline-plugin.js` should have a dedicated unit test, as this module is not trivial to understand, and will stay hard to maintain in the future (making changes with less confidence). 
2. it is unclear to me how you tested the performance before and after. can you please be very detailed about it?
fwiw, what i did was build master, then using another testing node module that imports it 

```json
// package.json for testing module
...
"dependencies": {
    "simple-xml-to-json": "file:../simple-xml-to-json"
  }
```

```js
// the testing script
'use strict'

const fs = require('fs')
const {convertXML} = require("simple-xml-to-json/lib/simpleXmlToJson.min.js")
// const {convertXML} = require("simple-xml-to-json")

const fileName = 'mock2.xml'
const fileToParse = fs.readFileSync(__dirname + "/" + fileName, {encoding: 'utf8'})

const start = Date.now()
const loops = 5000
for (let i = 0; i < loops; i++) {
    convertXML(fileToParse)
}
const end = Date.now()
console.log('average time for converting XML = ' + ((end-start)/loops) + 'ms')
```

surprisingly, i didn't see any difference in performance, so i'm not sure what i'm missing :\ 

thanks @jdalton for your contribution and patience 🙏🏻

🌿

2024-05-10 13:30 UTC, jdalton commented on scripts/inline-plugins.js
> +const inlinableCallExpressionReplacer = (match, funcName, args) => {
In this case its simulating string replace where a pattern is matched and then capture groups like funcName and args follow.

2024-05-10 13:31 UTC, jdalton commented on scripts/inline-plugins.js
> +        preventAssignment: false,
Making it `true` prevents replacement in `case: ` statements in `switch`s. As long as we aren't assigning to the constants this is fine to be `true`.

2024-05-10 13:34 UTC, jdalton commented
@nirgit 
> surprisingly, when i did the same on your branch, i didn't see any difference in performance, so i'm not sure what i'm missing :\

This branch is just adding the inline support but not yet taking advantage of it. That happens in the performance PR.

2024-05-10 13:34 UTC, merged